project2: project2.o fraction.o 
	g++ -o project2 project2.o fraction.o

project2.o: project2.cc fraction.h stack.h dictionary.h 
	g++ -c project2.cc 

fraction.o: fraction.cc fraction.h
	g++ -c fraction.cc 
